# docker-compose.yml
version: '2'

services:
  mlflow_server:
    build: 
      context: ./.docker/mlflow_server
      dockerfile: Dockerfile
    container_name: mlflow_server
    environment:
      - BACKEND_URI=/mlflow/store
      - ARTIFACT_ROOT=/mlflow/mlflow-artifacts
    ports:
      - "8888:5000"
    volumes:
      - mlflow_server_store:/mlflow
    networks:
      - backend

  kedro_pipeline:
    build: 
      context: .
      dockerfile: ./.docker/asi_project/Dockerfile
    container_name: kedro_pipeline
    networks:
      - backend
    volumes:
      - mlflow_server_store:/mlflow
      - ./:/kedro
    depends_on:
      - mlflow_server
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow_server:5000
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./.docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
    networks:
      - backend

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    container_name: cadvisor
    privileged: true
    platform: linux/aarch64
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - backend

volumes:
  mlflow_server_store:

networks:
  backend: